In [1]:
# Import necessary modules
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import matplotlib as mpl

# For balancing data
from imblearn.over_sampling import SMOTE

In [2]:
diseases_df = pd.read_csv('diseases.csv')
diseases_df.head()

,fever,headache,nausea,vomiting,fatigue,joint_pain,skin_rash,cough,weight_loss,yellow_eyes,disease
0,1,0,1,0,1,0,0,1,1,0,Paralysis (brain hemorrhage)
1,0,0,1,0,0,0,1,1,0,0,Paralysis (brain hemorrhage)
2,0,0,1,0,1,0,1,1,0,0,Paralysis (brain hemorrhage)
3,0,0,1,1,1,0,1,1,1,1,Paralysis (brain hemorrhage)
4,1,0,1,0,1,0,0,0,1,1,Paralysis (brain hemorrhage)

In [3]:
X = diseases_df.drop(['disease'], axis=1)
X.head()

,fever,headache,nausea,vomiting,fatigue,joint_pain,skin_rash,cough,weight_loss,yellow_eyes
0,1,0,1,0,1,0,0,1,1,0
1,0,0,1,0,0,0,1,1,0,0
2,0,0,1,0,1,0,1,1,0,0
3,0,0,1,1,1,0,1,1,1,1
4,1,0,1,0,1,0,0,0,1,1

In [4]:
y = diseases_df['disease']
y.head()

0    Paralysis (brain hemorrhage)
1    Paralysis (brain hemorrhage)
2    Paralysis (brain hemorrhage)
3    Paralysis (brain hemorrhage)
4    Paralysis (brain hemorrhage)
Name: disease, dtype: object

In [6]:
# Split the data
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3
)

oversample = SMOTE()
X_train, y_train = oversample.fit_resample(X_train, y_train)

In [8]:
# Linear SVC, KNeighborsClassifier, SVC, Ensemble Classifiers

In [9]:
C = 10
classifiers = {
    'Linear SVC': SVC(kernel='linear', C=C, probability=True, random_state=0),
    'KNN Classifier': KNeighborsClassifier(10),
    'SVC': SVC(),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100)
}

In [15]:
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [0.01, 0.1, 1, 5, 10, 20, 100]}
grid = GridSearchCV(
    SVC(kernel='linear'),
    param_grid,
    scoring='f1_macro',
    cv=5,
    n_jobs = -1
)

grid.fit(X_train, y_train)
print(grid.best_params_)

{'C': 10}

In [11]:
n_classifiers = len(classifiers)

for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train, y_train)

    print(name)
    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("Accuracy for %s: %0.1f%% "% (name, accuracy * 100))
    print(classification_report(y_test, y_pred))

Linear SVC
Accuracy for Linear SVC: 41.8%
                                                precision    recall  f1-score   support

                                          AIDS       0.44      0.80      0.57        10
                                          Acne       0.44      0.36      0.40        11
                           Alcoholic hepatitis       0.20      0.50      0.29         2
                                       Allergy       0.33      0.33      0.33        12
                                     Arthritis       0.36      0.40      0.38        10
                              Bronchial Asthma       0.40      0.43      0.41        14
                          Cervical spondylosis       0.52      0.48      0.50        23
                           Chronic cholestasis       0.27      0.43      0.33        14
                                        Dengue       0.15      0.27      0.19        11
                                      Diabetes       0.57      0.25      0.35        16
                  Dimorphic hemorrhoids(piles)       0.50      0.42      0.45        24
                                 Drug Reaction       0.50      0.69      0.58        13
                                          GERD       0.00      0.00      0.00        12
                               Gastroenteritis       0.29      0.38      0.33        13
                                  Heart attack       0.40      0.53      0.45        19
                                   Hepatitis A       0.50      0.58      0.54        12
                                   Hepatitis B       0.53      0.52      0.52        31
                                   Hepatitis C       0.36      0.62      0.46        13
                                   Hepatitis D       0.41      0.78      0.54         9
                                   Hepatitis E       0.42      0.71      0.53         7
                                  Hypertension       0.40      0.25      0.31        24
                               Hyperthyroidism       0.56      0.45      0.50        20
                                  Hypoglycemia       0.44      0.53      0.48        15
                                Hypothyroidism       0.08      0.10      0.09        10
                                      Impetigo       0.50      0.52      0.51        29
                                      Jaundice       0.30      0.33      0.32         9
                                       Malaria       0.59      0.48      0.53        21
                                      Migraine       0.18      0.14      0.16        14
                                Osteoarthritis       0.36      0.29      0.32        17
                  Paralysis (brain hemorrhage)       0.73      0.28      0.40        29
                          Peptic ulcer disease       0.43      0.69      0.53        13
                                     Pneumonia       0.31      0.29      0.30        17
                                     Psoriasis       0.57      0.29      0.38        14
                                  Tuberculosis       0.56      0.50      0.53        20
                                       Typhoid       0.48      0.60      0.54        25
                       Urinary tract infection       0.86      0.43      0.57        14
                                Varicose veins       0.14      0.07      0.09        15
Vertigo (Benign paroxysmal Positional Vertigo)       0.33      0.33      0.33        18

                                      accuracy                           0.42       600
                                     macro avg       0.41      0.42      0.40       600
                                  weighted avg       0.44      0.42      0.41       600

KNN Classifier
Accuracy for KNN Classifier: 37.0%
                                                precision    recall  f1-score   support

                                          AIDS       0.47      0.70      0.56        10
                                          Acne       0.22      0.36      0.28        11
                           Alcoholic hepatitis       0.14      0.50      0.22         2
                                       Allergy       0.10      0.08      0.09        12
                                     Arthritis       0.16      0.30      0.21        10
                              Bronchial Asthma       0.32      0.43      0.36        14
                          Cervical spondylosis       0.38      0.48      0.42        23
                           Chronic cholestasis       0.33      0.50      0.40        14
                                        Dengue       0.13      0.36      0.19        11
                                      Diabetes       0.28      0.31      0.29        16
                  Dimorphic hemorrhoids(piles)       0.45      0.38      0.41        24
                                 Drug Reaction       0.60      0.69      0.64        13
                                          GERD       0.25      0.17      0.20        12
                               Gastroenteritis       0.15      0.23      0.18        13
                                  Heart attack       0.50      0.37      0.42        19
                                   Hepatitis A       0.67      0.33      0.44        12
                                   Hepatitis B       0.52      0.52      0.52        31
                                   Hepatitis C       0.35      0.62      0.44        13
                                   Hepatitis D       0.32      0.67      0.43         9
                                   Hepatitis E       0.33      0.71      0.45         7
                                  Hypertension       0.26      0.21      0.23        24
                               Hyperthyroidism       0.46      0.30      0.36        20
                                  Hypoglycemia       0.62      0.53      0.57        15
                                Hypothyroidism       0.14      0.10      0.12        10
                                      Impetigo       0.48      0.52      0.50        29
                                      Jaundice       0.22      0.22      0.22         9
                                       Malaria       0.38      0.29      0.32        21
                                      Migraine       0.17      0.07      0.10        14
                                Osteoarthritis       0.18      0.12      0.14        17
                  Paralysis (brain hemorrhage)       0.56      0.31      0.40        29
                          Peptic ulcer disease       0.33      0.08      0.12        13
                                     Pneumonia       0.31      0.29      0.30        17
                                     Psoriasis       0.57      0.29      0.38        14
                                  Tuberculosis       0.46      0.55      0.50        20
                                       Typhoid       0.60      0.60      0.60        25
                       Urinary tract infection       0.86      0.43      0.57        14
                                Varicose veins       0.18      0.13      0.15        15
Vertigo (Benign paroxysmal Positional Vertigo)       0.62      0.28      0.38        18

                                      accuracy                           0.37       600
                                     macro avg       0.37      0.37      0.35       600
                                  weighted avg       0.40      0.37      0.37       600

SVC
Accuracy for SVC: 39.5%
                                                precision    recall  f1-score   support

                                          AIDS       0.50      0.70      0.58        10
                                          Acne       0.33      0.36      0.35        11
                           Alcoholic hepatitis       0.17      0.50      0.25         2
                                       Allergy       0.25      0.08      0.12        12
                                     Arthritis       0.33      0.30      0.32        10
                              Bronchial Asthma       0.33      0.43      0.38        14
                          Cervical spondylosis       0.40      0.52      0.45        23
                           Chronic cholestasis       0.32      0.50      0.39        14
                                        Dengue       0.19      0.36      0.25        11
                                      Diabetes       0.43      0.19      0.26        16
                  Dimorphic hemorrhoids(piles)       0.52      0.46      0.49        24
                                 Drug Reaction       0.39      0.54      0.45        13
                                          GERD       0.25      0.08      0.12        12
                               Gastroenteritis       0.32      0.46      0.38        13
                                  Heart attack       0.53      0.42      0.47        19
                                   Hepatitis A       0.40      0.50      0.44        12
                                   Hepatitis B       0.54      0.48      0.51        31
                                   Hepatitis C       0.40      0.62      0.48        13
                                   Hepatitis D       0.43      0.67      0.52         9
                                   Hepatitis E       0.21      0.57      0.31         7
                                  Hypertension       0.47      0.29      0.36        24
                               Hyperthyroidism       0.50      0.50      0.50        20
                                  Hypoglycemia       0.42      0.53      0.47        15
                                Hypothyroidism       0.12      0.10      0.11        10
                                      Impetigo       0.47      0.48      0.47        29
                                      Jaundice       0.27      0.33      0.30         9
                                       Malaria       0.53      0.48      0.50        21
                                      Migraine       0.18      0.14      0.16        14
                                Osteoarthritis       0.24      0.24      0.24        17
                  Paralysis (brain hemorrhage)       0.53      0.28      0.36        29
                          Peptic ulcer disease       0.39      0.54      0.45        13
                                     Pneumonia       0.38      0.29      0.33        17
                                     Psoriasis       0.60      0.21      0.32        14
                                  Tuberculosis       0.39      0.45      0.42        20
                                       Typhoid       0.42      0.56      0.48        25
                       Urinary tract infection       0.86      0.43      0.57        14
                                Varicose veins       0.12      0.07      0.09        15
Vertigo (Benign paroxysmal Positional Vertigo)       0.42      0.28      0.33        18

                                      accuracy                           0.40       600
                                     macro avg       0.38      0.39      0.37       600
                                  weighted avg       0.41      0.40      0.39       600

RFST
Accuracy for RFST: 35.0%
                                                precision    recall  f1-score   support

                                          AIDS       0.44      0.80      0.57        10
                                          Acne       0.22      0.18      0.20        11
                           Alcoholic hepatitis       0.14      0.50      0.22         2
                                       Allergy       0.09      0.08      0.09        12
                                     Arthritis       0.21      0.30      0.25        10
                              Bronchial Asthma       0.25      0.36      0.29        14
                          Cervical spondylosis       0.46      0.57      0.51        23
                           Chronic cholestasis       0.32      0.50      0.39        14
                                        Dengue       0.17      0.27      0.21        11
                                      Diabetes       0.36      0.25      0.30        16
                  Dimorphic hemorrhoids(piles)       0.60      0.38      0.46        24
                                 Drug Reaction       0.50      0.46      0.48        13
                                          GERD       0.20      0.08      0.12        12
                               Gastroenteritis       0.24      0.31      0.27        13
                                  Heart attack       0.43      0.47      0.45        19
                                   Hepatitis A       0.42      0.42      0.42        12
                                   Hepatitis B       0.52      0.35      0.42        31
                                   Hepatitis C       0.42      0.62      0.50        13
                                   Hepatitis D       0.30      0.67      0.41         9
                                   Hepatitis E       0.25      0.57      0.35         7
                                  Hypertension       0.42      0.21      0.28        24
                               Hyperthyroidism       0.28      0.25      0.26        20
                                  Hypoglycemia       0.36      0.27      0.31        15
                                Hypothyroidism       0.07      0.10      0.08        10
                                      Impetigo       0.46      0.45      0.46        29
                                      Jaundice       0.27      0.33      0.30         9
                                       Malaria       0.43      0.29      0.34        21
                                      Migraine       0.18      0.14      0.16        14
                                Osteoarthritis       0.09      0.06      0.07        17
                  Paralysis (brain hemorrhage)       0.40      0.28      0.33        29
                          Peptic ulcer disease       0.50      0.54      0.52        13
                                     Pneumonia       0.26      0.35      0.30        17
                                     Psoriasis       0.27      0.21      0.24        14
                                  Tuberculosis       0.38      0.40      0.39        20
                                       Typhoid       0.48      0.60      0.54        25
                       Urinary tract infection       0.64      0.50      0.56        14
                                Varicose veins       0.22      0.13      0.17        15
Vertigo (Benign paroxysmal Positional Vertigo)       0.31      0.22      0.26        18

                                      accuracy                           0.35       600
                                     macro avg       0.33      0.35      0.33       600
                                  weighted avg       0.36      0.35      0.34       600

ADA
Accuracy for ADA: 24.0%
                                                precision    recall  f1-score   support

                                          AIDS       0.00      0.00      0.00        10
                                          Acne       0.13      0.55      0.21        11
                           Alcoholic hepatitis       0.00      0.00      0.00         2
                                       Allergy       0.25      0.25      0.25        12
                                     Arthritis       0.05      0.10      0.06        10
                              Bronchial Asthma       0.00      0.00      0.00        14
                          Cervical spondylosis       0.33      0.30      0.32        23
                           Chronic cholestasis       0.00      0.00      0.00        14
                                        Dengue       0.17      0.18      0.17        11
                                      Diabetes       0.40      0.25      0.31        16
                  Dimorphic hemorrhoids(piles)       0.32      0.38      0.35        24
                                 Drug Reaction       0.58      0.85      0.69        13
                                          GERD       0.17      0.08      0.11        12
                               Gastroenteritis       0.36      0.38      0.37        13
                                  Heart attack       0.39      0.58      0.47        19
                                   Hepatitis A       0.23      0.25      0.24        12
                                   Hepatitis B       0.00      0.00      0.00        31
                                   Hepatitis C       0.32      0.54      0.40        13
                                   Hepatitis D       0.28      0.56      0.37         9
                                   Hepatitis E       0.25      0.14      0.18         7
                                  Hypertension       0.20      0.12      0.15        24
                               Hyperthyroidism       0.22      0.20      0.21        20
                                  Hypoglycemia       0.38      0.33      0.36        15
                                Hypothyroidism       0.25      0.10      0.14        10
                                      Impetigo       0.31      0.59      0.41        29
                                      Jaundice       0.00      0.00      0.00         9
                                       Malaria       0.23      0.14      0.18        21
                                      Migraine       0.07      0.07      0.07        14
                                Osteoarthritis       0.00      0.00      0.00        17
                  Paralysis (brain hemorrhage)       0.34      0.38      0.36        29
                          Peptic ulcer disease       0.12      0.15      0.13        13
                                     Pneumonia       0.22      0.12      0.15        17
                                     Psoriasis       0.20      0.14      0.17        14
                                  Tuberculosis       0.75      0.15      0.25        20
                                       Typhoid       0.08      0.12      0.10        25
                       Urinary tract infection       0.25      0.21      0.23        14
                                Varicose veins       0.03      0.07      0.04        15
Vertigo (Benign paroxysmal Positional Vertigo)       0.24      0.39      0.30        18

                                      accuracy                           0.24       600
                                     macro avg       0.21      0.23      0.20       600
                                  weighted avg       0.23      0.24      0.22       600

C:\Users\Wendy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Wendy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Wendy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [16]:
# Linear SVC performs best
from sklearn.svm import SVC

linear_svc = SVC(
    kernel="linear",
    C=10,
    class_weight="balanced",
    random_state=42
)

linear_svc.fit(X_train, y_train)

SVC(C=10, class_weight='balanced', kernel='linear', random_state=42)

In [40]:
from sklearn.metrics import f1_score

y_pred = linear_svc.predict(X_test)

# print(classification_report(y_test, y_pred))
print(f1_score(y_test, y_pred, average='weighted'))

0.4115246283539696

In [19]:
possible_symptoms = ['fever', 'headache', 'nausea', 'vomiting', 'fatigue', 'joint_pain', 'skin_rash', 'cough', 'weight_loss', 'yellow_eyes']

def predict_top_10_diseases(symptoms):
    input_data = [0] * len(possible_symptoms)

    for symptom in symptoms.split(','):
        symptom = symptom.strip()

        if symptom in possible_symptoms:
            idx = possible_symptoms.index(symptom)
            input_data[idx] = 1

        sample = pd.DataFrame([input_data], columns=X_train.columns)

        # Get decision scores
        scores = linear_svc.decision_function(sample)[0]

        # Get indices of top 10 scores
        top_10_idx = np.argsort(scores)[-10:][::-1]

        # Map indices to disease names and scores
        top_10_diseases = [
            (linear_svc.classes_[i], scores[i])
            for i in top_10_idx
        ]

        return top_10_diseases

In [31]:
symptoms = "fever,nausea"
top_10 = predict_top_10_diseases(symptoms)

for disease, score in top_10:
    print(f"{disease:40s} confidence score: {score:.3f}")

Pneumonia                                confidence score: 37.330
Diabetes                                 confidence score: 36.330
Urinary tract infection                  confidence score: 34.327
Jaundice                                 confidence score: 33.327
Psoriasis                                confidence score: 32.327
Tuberculosis                             confidence score: 31.327
Arthritis                                confidence score: 30.326
Hyperthyroidism                          confidence score: 30.326
Vertigo (Benign paroxysmal Positional Vertigo) confidence score: 27.322
Dengue                                   confidence score: 26.315

In [33]:
def top_k_accuracy(model, X_test, y_test, k=10):
    scores = model.decision_function(X_test)
    top_k_preds = np.argsort(scores, axis=1)[:, -k:]

    correct = 0
    for i, true_label in enumerate(y_test):
        true_index = np.where(model.classes_ == true_label)[0][0]
        if true_index in top_k_preds[i]:
            correct += 1

    return correct / len(y_test)

In [36]:
acc = top_k_accuracy(linear_svc, X_test, y_test, k=10)
print(f"Accuracy: {acc * 100:.2f}%")

Accuracy: 89.50%